name: Terraform Static Web App Deploy

on:
  push:
    branches: 
      - main

permissions:
  id-token: write
  contents: read

env:
  TERRAFORM_OUTPUTS_PATH: 'terraform-outputs'
  TERRAFORM_SWA_SECRET_PATH: 'swa-secret.txt'
  TERRAFORM_PUBLISH_PROFILE_PATH: 'publish-profile.txt'
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ SECRETS.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ SECRETS.AZURE_TENANT_ID }}
  AZURE_WEBAPP_NAME: minimal-terraform-spa-api  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './api'      # set this to the path to your web app project, defaults to the repository root

jobs:
  terraform_plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:

      - uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color -input=false
  
  terraform_apply:
    name: 'terraform apply'
    needs: [terraform_plan]
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash
        
    steps:
    - uses: actions/checkout@v4

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      
    - name: Load ${{ env.TERRAFORM_SWA_SECRET_PATH }}
      run: |
        mkdir -p ${{ env.TERRAFORM_OUTPUTS_PATH }}
        terraform output swa-api-key > ${{ env.TERRAFORM_OUTPUTS_PATH }}/${{ env.TERRAFORM_SWA_SECRET_PATH }}
    
    - name: Load ${{ env.TERRAFORM_PUBLISH_PROFILE_PATH }}
      run: |
        mkdir -p ${{ env.TERRAFORM_OUTPUTS_PATH }}
        terraform output webapp-site-credential > ${{ env.TERRAFORM_OUTPUTS_PATH }}/${{ env.TERRAFORM_PUBLISH_PROFILE_PATH }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.TERRAFORM_OUTPUTS_PATH }}
        path: ${{ env.TERRAFORM_OUTPUTS_PATH }}

  build_and_deploy_web:
    name: 'build and deploy web'
    needs: [terraform_apply]
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash

    steps:
      
      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ${{ env.TERRAFORM_OUTPUTS_PATH }}
          path: ${{ env.TERRAFORM_OUTPUTS_PATH }}
    
      - name: Load SWA Secret
        id: load-secret
        run: echo "swa-secret=$(cat ${{ env.TERRAFORM_OUTPUTS_PATH }}/${{ env.TERRAFORM_SWA_SECRET_PATH }})" >> $GITHUB_OUTPUT

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build
        run: |
          npm install
          npm run build:prod --if-present
        working-directory: web
      
      - name: Deploy
        run: npx @azure/static-web-apps-cli@1.1.6 deploy ./dist/web/ --env production --deployment-token ${{ steps.load-secret.outputs.swa-secret }}
        working-directory: web

  build_and_deploy_api:
    name: 'build and deploy api'
    needs: [terraform_apply]
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash

    steps:

      - uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ${{ env.TERRAFORM_OUTPUTS_PATH }}
          path: ${{ env.TERRAFORM_OUTPUTS_PATH }}
    
      - name: Load SWA Secret
        id: load-secret
        run: echo "publish-profile=$(cat ${{ env.TERRAFORM_OUTPUTS_PATH }}/${{ env.TERRAFORM_PUBLISH_PROFILE_PATH }})" >> $GITHUB_OUTPUT

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        working-directory: api

      # - name: Zip artifact for deployment
      #   run: zip release.zip ./* -r
      #   working-directory: api

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          publish-profile: ${{ steps.load-secret.outputs.publish-profile }}

      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ env.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'

      # - name: Azure CLI script
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az accounts