name: Azure Static Web Apps CI/CD

on:
  push:
    branches: 
      - main

env:
  ROOT_PATH: '${{github.workspace}}'
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ SECRETS.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ SECRETS.AZURE_TENANT_ID }}

jobs:
  terraform_plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.ROOT_PATH }}

      - name: Terraform Plan
        run: terraform plan -no-color -input=false
        working-directory: ${{ env.ROOT_PATH }}
  
  terraform_apply:
    name: 'terraform apply'
    needs: [terraform_plan]
    runs-on: ubuntu-latest
    environment: production
    
    defaults:
      run:
        shell: bash
        
    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH }}

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: ${{ env.ROOT_PATH }}
  
  # build_and_deploy:
  #   name: 'build and deploy'
  #   needs: [terraform_apply]
  #   runs-on: ubuntu-latest
  #   environment: production
    
  #   defaults:
  #     run:
  #       shell: bash
        
  #   steps:
      
    - name: Load Secret
      id: show-secret
      run: terraform output sample-web-api-key

    - name: Show Secret
      run: echo "Secret ${{ steps.show-secret.outputs.stdout }}"
    
    - name: Show Secret
      run: echo "Secret ${{ secrets.GITHUB_TOKEN }}"
      
      # - name: Build And Deploy
      #   id: builddeploy
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ steps.show-secret.outputs.stdout }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
      #     action: "upload"
      #     ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
      #     # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      #     app_location: "/web" # App source code path
      #     api_location: "" # Api source code path - optional
      #     output_location: "dist/web" # Built app content directory - optional
      #     app_build_command: npm run build:prod
      #     ###### End of Repository/Build Configurations ######