name: Azure Static Web Apps CI/CD

on:
  push:
    branches: 
      - main
  # workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   types: [opened, synchronize, reopened, closed]
  #   branches:
  #     - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color
      
      - id: show-secret
        run: terraform output sample-web-api-key
      
      - run: |
          echo "${{ steps.show-secret.outputs.stdout }}"