name: Azure Static Web Apps CI/CD

on:
  push:
    branches: 
      - main
  # workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   types: [opened, synchronize, reopened, closed]
  #   branches:
  #     - main

jobs:
  build_and_deploy_job:
    name: Build and Deploy Job
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ SECRETS.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ SECRETS.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: .
    
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      # - name: Log in with Azure
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ SECRETS.AZURE_SUBSCRIPTION_ID }}
      #     enable-AzPSSession: true

      #   creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false
        continue-on-error: true
      
      - name: Load Secret
        id: show-secret
        run: terraform output sample-web-api-key

      - name: Show Secret
        run: echo "Secret ${{ steps.show-secret.outputs.stdout }}"
      
      # - name: Build And Deploy
      #   id: builddeploy
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ steps.show-secret.outputs.stdout }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
      #     action: "upload"
      #     ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
      #     # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      #     app_location: "/web" # App source code path
      #     api_location: "" # Api source code path - optional
      #     output_location: "dist/web" # Built app content directory - optional
      #     app_build_command: npm run build:prod
      #     ###### End of Repository/Build Configurations ######